DOMAIN = "sia_transmitter"
TITLE = "SIA Alarm on port {}"
CONF_HOST = "host" # Can be removed and use home assistant built in instead
CONF_PORT = "port" # Can be removed and use home assistant built in instead
CONF_ACCOUNT_ID = "account_id"
CONF_SUPERVISION = "enable_supervision"
CONF_INTERVAL = "interval"
CONF_ADDITIONAL_ACCOUNTS = "additional_account"
CONF_ACCOUNTS = "accounts"
CONF_ACCOUNT = "account"
SERVICE_SEND_SIA_NAME = "service_send_sia"