service_send_sia:
  name: Send SIA message
  description: Send an SIA message to the current host with a message
  fields:
    message:
      name: Message
      description: The data to send, often the account ID with an event code
      example: "#54321|NFA128"
      required: false
      selector:
        text:
